#!/bin/bash
###
#
# QUICK CALL SCRIPT TO START MYSQL SERVER CONTAINER
# CALL THIS SCRIPT FROM ~/sandbox/
#   ./assets.docker/<APPLICATION>/this_script
# PASS -cli AS $1 FOR BASH SHELL
#
###

scriptname=$(basename $0)
DIR=$(echo ${0} | sed "s/\/${scriptname}//")

. ${DIR}/setenv
if [ ! ${ENV} ]; then ENV=dev; fi
if [ ! ${OS} ]; then OS=centos8; fi

run --env=${ENV} --purpose=database --app=${APP} ${1} mysql/mysql-server:5.7
