#!/bin/bash
#grocery_data_generator
CUSER=${GITUSER}
echo -e "using ${CUSER} for clone\nenter appname: " && read app
mkdir -p ./${app}/assets.docker

# HARD LINK PRIVATE ASSETS
for f in $(/bin/ls -A ./private.assets/|grep -vE '.gitignore$'); do ln -fn ./private.assets/$f ./${app}/assets.docker/; done
# HARD LINK RUN FILES
for f in dobuild rundb rundev; do ln -fn ./generic/$f ./${app}/; done

cp ./generic/Dockerfile.centos8.sh ./${app}/
mkdir -p ../assets.${app}-application && echo '*' >${_}/.gitignore

# SYM LINK THE SANDBOX -APP DIR
ln -fsn ~/Docker/assets.${app}-application ~/sandbox/assets.docker/${app}

# COPY AND CHANGE ENV FILE
cp ./generic/setenv ${app}/
sed -i '' "s/generic/${app}/" ${app}/setenv
ln -fn ${app}/setenv ~/sandbox/assets.docker/${app}/


# SYM LINK THE EXECUTABLES TO THE SANDBOX
for f in setenv dobuild rundb rundev; do ln -fsn ${PWD}/${app}/$f ~/sandbox/assets.docker/${app}/ ;done
git clone git@github.com:${CUSER}/${app} ~/Docker/assets.${app}-application/${app}
