#!/bin/bash

function msg {
  echo "  buildall says: ${1}"
}
function init { #
  for path in ~/Docker/root_docker/node_r_admin ~/Docker/root_docker/awsdev_r_admin ~/Docker/root_docker/terraform_r_admin ~/Docker/root_docker/kubernetes_r_admin ~/Docker/root_docker/docker_r_admin ~/Docker/root_docker/development_r_admin ~/Docker/root_docker/ubuntu_seed_r_admin ~/Docker/root_docker/ubuntu_seed_r_admin
  do pushd ${path} > /dev/null; done
}

function do_build {
   if [ -f ./Dockerfile ]; then
      msg "doing docker build ${1}"
     while ! docker build -t ${1} . > /dev/null; do
       msg -n "Error in ${1}, fix then press <Enter> to retry";
       read x; msg "Retrying ${1}";
     done
   fi
}
function build {
  tag=$1
  if [[ ${tag} == ubuntu_seed_r_admin ]];
    then do_build ${tag} \
      && tag=${tag}:20.04; do_build ${tag}
    else do_build ${tag}
  fi
}

# - main
if [ ${1} ]
then pushd ~/Docker/root_docker/${1}_r_admin
  build "${1}_r_admin"
  popd
else init
  while popd > /dev/null 2>&1; do d=`pwd | sed 's|.*/||'`
    if [[ ${d} == Docker ]]; then break; fi;
    build ${d}
  done
fi
