apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: majikl-disappearing-cluster
  region: us-east-1

nodeGroups:
  - name: ng-mixed
    minSize: 3
    maxSize: 5
    instancesDistribution:
      maxPrice: 0.2
      instanceTypes: ["t2.small", "t3.small"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
    ssh:
      publicKeyName: eks-course-ec2-keypair
