#!/bin/bash
###
#
# QUICK CALL SCRIPT TO START MYSQL SERVER CONTAINER
# CALL THIS SCRIPT FROM ~/sandbox/
#   ./assets.docker/<APPLICATION>/this_script
# PASS -cli AS $1 FOR BASH SHELL
#
###

scriptname=$(basename $0)
DIR=$(echo ${0} | sed "s/\/${scriptname}//")

. ${DIR}/setenv
if [ ! ${ENV} ]; then ENV=dev; fi
if [ ! ${OS} ]; then OS=centos8; fi
if [ ! ${DB} ]; then DB=mysql/mysql-server:5.7; fi
if [ $# -eq 1 ]; then DEBUG=$1; fi



CMD="DEBUG=${DEBUG} run --env=${ENV} --purpose=database --container=${APP} --app=${APP} ${DBPORT} ${DETACHDB} ${NAMEDCONTAINER} ${DBINTERACTIVE} \"${ENVVAR}\" ${DB}"

#echo ${CMD} && exit 1
eval ${CMD}
