version: '2'
services:
  spark-master:
    image: local/spark-master:3.0.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - docker-spark_datashare:/data
    environment:
      - INIT_DAEMON_STEP=setup_spark
    hostname: spark-master
  spark-worker-1:
    image: local/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - docker-spark_datashare:/data
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    hostname: spark-worker-1
  spark-worker-2:
    image: local/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - docker-spark_datashare:/data
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    hostname: spark-worker-2
  spark-worker-3:
    image: local/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    volumes:
      - docker-spark_datashare:/data
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    hostname: spark-worker-3
volumes:
    docker-spark_datashare:
