#!/bin/bash
scriptname=$(basename $0)
DIR=$(echo ${0} | sed "s/\/${scriptname}//")

. ${DIR}/setenv
if [ ! ${ENV} ]; then ENV=dev; fi
if [ ! ${OS} ]; then OS=centos8; fi
OS=.${OS}

build --arg=APP=${APP} --arg=gituser=${CUSER} --arg=SSH_PRIVATE_KEY=${KEYNAME} ${LOCALUSER} --key SSH_PRIVATE_KEY_STREAM ${KEYPATH} -f Dockerfile${OS} ${1} Applications/${APP}
